---
# Tools that can save round-trips to github and a lot of time:
#
# yamllint -f parsable pull_request.yml
# pip3 install ruamel.yaml.cmd
# yaml merge-expand pull_request.yml exp.yml &&
#    diff -w -u pull_request.yml exp.yml
#
# github.com also has a powerful web editor that can be used without
# committing.


name: main test

# 'workflow_dispatch' allows running this workflow manually from the
# 'Actions' tab
# yamllint disable-line rule:truthy
on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}

    strategy:
      fail-fast: false
      # matrix is very flexible and not always "obvious"
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflo
      matrix:
        # - img_distro/img_rel: keep it simple and just build "ourselves"
        # - mkosi_ver: the goal is NOT to test a large range of mkosi versions.
        #   Most of them fail in obscure ways. This is about testing run_qemu
        #   and finding some mkosi versions good enough for that.
        #   - This is about testing run_qemu, not mkosi
        #   - This is only about catching major run_qemu regressions. This is not "validation", it's only CI
        # mkosi on Ubuntu 24.04 is incredibly brittle: every mkosi version fails in a slightly different way.
        # Generally speaking, mkosi developers don't seem to care about Ubuntu much - and vice versa.
        # Patch v20 to catch accidentally introduced dependencies on newer mkosi versions
        cfg:
          - os: ubuntu-22.04
            img_distro: ubuntu
            img_rel: jammy
            mkosi_ver: os_default
          - os: ubuntu-24.04
            img_distro: ubuntu
            img_rel: noble
            mkosi_ver: v24.3
        arch: [x86_64]
        run_opts: [--cxl]

    steps:
      - uses: actions/checkout@v4
        with:
          path: run_qemu

      - name: apt get requirements
        run: |
          # update is required first, see
          # https://github.com/actions/runner-images/issues/2924
          sudo apt-get update

          # Kernel deps
          sudo apt install -y build-essential flex bison libelf-dev libssl-dev

          # run_qemu deps
          sudo apt install -y mkosi # this one pulls A LOT
          sudo apt install -y dracut-core qemu-utils ovmf mtools

      - name: mkosi v20 fixes
        if: matrix.cfg.os  == 'ubuntu-24.04'
        run: |
          cd /usr/lib/python3/dist-packages
          sudo git apply "${{ github.workspace }}"/run_qemu/Patches/ubuntu/24.04/mkosi/*.patch

      - name: apt get Ubuntu 24 requirements
        if: matrix.cfg.os  == 'ubuntu-24.04'
        run: |
           # systemd was monolithic in Ubunutu 22
           sudo apt install -y systemd-ukify systemd-boot

      - name: git clone mkosi
        if: matrix.cfg.mkosi_ver  != 'os_default'
        uses: actions/checkout@v4
        with:
          repository: systemd/mkosi
          ref: ${{ matrix.cfg.mkosi_ver }}
          path: mkosi

      - name: mkosi switch
        run: |
          sudo dpkg --purge mkosi
          # This is a throw-away container; don't do this at home.
          # Try a couple symlinks instead, see corresponding mkosi/README.md
          cd mkosi && sudo pip install --break-system-packages -e .

      # argbash. TODO: mixing generated code and sources in the same git
      # repo is generally a bad idea but this particular one changes
      # rarely, so it should probably deserve an exception avoiding
      # everyone this step.
      - name: argbash
        run: |
          AB_VER=2.10.0
          wget https://github.com/matejak/argbash/archive/refs/tags/${AB_VER}.tar.gz
          tar xf ${AB_VER}.tar.gz
          sudo apt install -y autoconf
          sudo make -C argbash-${AB_VER}/resources install PREFIX=/usr/local/

      - name: download kernel
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v6.12
          path: kernel

      - name: defconfig
        run: cd kernel &&
          make defconfig ARCH=${{ matrix.arch }}

      - name: disable AppArmor
        run: |
          # Bubblewrap needs this for RTM_NEWADDR. This may not be required in
          # this GitHub runner/container but it's still useful as "documentation"
          # https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
          if test -e /proc/sys/kernel/apparmor_restrict_unprivileged_unconfined; then
                    sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
                    sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          fi

      - name: build
        run: |
          mkosi --version
          cd kernel
          distro=${{ matrix.cfg.img_distro }} rev=${{ matrix.cfg.img_rel }} \
                 ../run_qemu/run_qemu.sh -v --no-run ${{ matrix.run_opts }}

      # TODO: drop --no-run thanks to "nested KVM" or something?
